# Generated by Django 4.2.2 on 2023-07-06 11:02

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='img_post', variations={'medium': (400, 300)}),
        ),
    ]
